name: miwifi_util
description: A command-line utility tool to access your Xiaomi router.
version: 1.0.0
repository: https://github.com/RA1NO3O/miwifi_util.git
executables:
  miwifi_util: bin/miwifi_util.dart
publish_to: none
platforms:
  linux:
  macos:
  windows:


environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  crypto: ^3.0.6
  convert: ^3.1.2
  args: ^2.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
